### PR TITLE
maintain url_type on new resources

### PR DESCRIPTION
**Pull request by wardi**

### CODE REVIEW

**Comment by wardi** [comment]
@JVickery-TBS this reverts part of 2ac90864476c1c641b0cdff4d8527c64a3dd39ec

**Comment by JVickery-TBS** [comment]
@wardi sounds good. Yeah I did not fully understand the cherry-picked changes to that file and the setting of the `url_type`.

**Comment by wardi** [comment]
I was trying to find an upstream to contribute the fix to but only found your commit. Did you cherry-pick from one of the maintained forks?

**Comment by JVickery-TBS** [comment]
Yeah I believe it was from the datopian fork, ckan-2.9 branch. But I only needed that because we are still on python2. So not sure if that branch is even used in releases or not.

**Pull request merged**
