### PR TITLE
Changed `connection_link` property definition to just return the alre…

### PR DESCRIPTION
**Pull request by JVickery-TBS**
…ady loaded `driver_options`. Used `format` instead of `f` string for python2 support. Added more conditions for the `url_type` to issues with `url_type` not getting set correctly.

### CODE REVIEW

**Comment by wardi** [comment]
Looks good. thanks @JVickery-TBS

**Comment by wardi** [comment]
@JVickery-TBS is there something else to review? This LGTM

**Comment by JVickery-TBS** [comment]
@wardi Nope, these were the only changes I made to the fork, as well as bring in those master bug fixes.

So as long as this works with our ckan 2.9 setup we should hopefully be good to go.

I am not too sure how many diffs there are between `canada-v2.9` and our `master` though, as `canada-v2.9` is branched off of the datopian `ckan2.9` branch.

**Comment by wardi** [comment]
we can reset master if we need to when the time comes.

**Pull request merged**
